### ISSUE TITLE
Finding the beginning node in a circular linked list

### ISSUE THREAD

**Issue by GargNikitaa** [RitamPaul/Basic_Codes#22]

**Comment by GargNikitaa** [comment]
Want to want on this issue, pls assign this to me

**Comment by RitamPaul** [comment]
okay you can go on. create a folder with same name as of your program and inside it paste your actual source code file and a readme file to describe your code

**Comment by GargNikitaa** [comment]
https://github.com/RitamPaul/Basic_Codes/pull/24#issue-1419884892 @RitamPaul Pls have a look
