### ISSUE TITLE
Number Star Pattern

### ISSUE THREAD

**Issue by Jainsuhani2021** [RitamPaul/Basic_Codes#26]

**Comment by Jainsuhani2021** [comment]
https://github.com/RitamPaul/Basic_Codes/pull/25#issue-1428155764
@RitamPaul Sir please assign this issue to me

**Comment by RitamPaul** [comment]
@Jainsuhani2021 buddy write a line that "Enter the number of rows in single digit" before "cin>>n" statement, as your program is not making triangle like structure for 2 digit number input

**Comment by RitamPaul** [comment]
Your program is accepted
